---
java_config:
  path: lang/java
  brew_formulas:
    - maven
    - gradle
    - java
  brew_casks:
    - adoptopenjdk/openjdk/adoptopenjdk8
  brew_taps:
    - homebrew/cask-versions
    - adoptopenjdk/openjdk
  pacman_packages:
    - jdk-openjdk
    - jre-openjdk
    - maven
    - gradle
