---
java_config:
  path: lang/java
  brew_formulas:
    - maven
  brew_casks:
    - intellij-idea-ce
  osx_defaults:
    - domain: com.jetbrains.intellij.ce
      key: ApplePressAndHoldEnabled
      value: false
      type: bool
      state: present
