---
neovim_config:
  path: editor/neovim
  dirname: nvim
  brew_formulas:
    - neovim
  links:
    - init.vim
    - plugins.vim
    - general.vim
    - autocmds.vim
    - theme.vim
    - keybindings.vim
    - experimental.vim
    - plugins.d
    - UltiSnips
    - coc-settings.json
