---
neovim_config:
  path: editor/neovim
  dirname: nvim
  brew_formulas:
    - neovim
    - fzf
    - bat
    - python
  pacman_packages:
    - neovim
    - fzf
    - bat
    - python
  pip_packages:
    - pynvim
    - pylint
    - black
  links:
    - init.vim
    - plugins.vim
    - general.vim
    - autocmds.vim
    - theme.vim
    - keybindings.vim
    - experimental.vim
    - plugins.d
    - UltiSnips
    - coc-settings.json
    - src: coc-extensions.json
      dest: "{{ xdg_config_home }}/coc/extensions/package.json"
