---
neovim_config:
  path: editor/neovim
  dirname: nvim
  brew_formulas:
    - neovim
  links:
    - src: "{{ dotfiles_data }}/editor.vim.topic/.vimrc"
      absolute: true
      dest: "{{ xdg_config_home }}/nvim/init.vim"
