---
neovim_config:
  path: editor/neovim
  dirname: nvim
  brew_formulas:
    - neovim
    - fzf
    - bat
    - python
    - pylint
    - black
  pacman_packages:
    - neovim
    - fzf
    - bat
    - python
    - python-pylint
    - python-black
  aur_packages:
    - luafmt
    - glow
  npm_packages:
    - bash-language-server
    - diagnostic-languageserver
    - typescript
    - typescript-language-server
    - vscode-langservers-extracted
    - yaml-language-server
    - dockerfile-language-server-nodejs
    - pyright
  pip_packages:
    - pynvim
  links:
    - init.vim
    - plugins.vim
    - general.vim
    - autocmds.vim
    - theme.vim
    - keybindings.vim
    - experimental.vim
    - plugins.d
    - lua
    - UltiSnips
    - coc-settings.json
    - src: coc-extensions.json
      dest: "{{ xdg_config_home }}/coc/extensions/package.json"
