---
bspwm_config:
  path: wm/bspwm
  links:
    - bspwmrc
    - src: launch_on_desktop.sh
      dest: "{{ xdg_bin_home }}/"
      rename: launch_on_desktop
    - src: navigate.sh
      dest: "{{ xdg_bin_home }}/"
      rename: navigate
    - src: send_home.sh
      dest: "{{ xdg_bin_home }}/"
      rename: send_home
  pacman_packages:
    - bspwm
    - xdo
