---
- name: install homebrew
  debug:
    msg: "Not implemented"
  tags: install

# - block:
#     - debug:
#         var: brew.taps
#         verbosity: 1
#     - debug:
#         var: brew.formulas
#         verbosity: 1
#     - debug:
#         var: brew.casks
#         verbosity: 1
#   tags: always

- name: determine taps
  set_fact:
    brew_taps: "{{ q('dict', brew.taps) | map(attribute='value') | list | flatten | unique }}"
  when: brew.taps is defined
  tags: always

- name: determine casks
  set_fact:
    brew_casks: "{{ q('dict', brew.casks) | map(attribute='value') | list | flatten | unique }}"
  when: brew.casks is defined
  tags: always

- name: determine formulas
  set_fact:
    brew_formulas: "{{ q('dict', brew.formulas) | map(attribute='value') | list | flatten | unique }}"
  when: brew.formulas is defined
  tags: always

# - block:
#     - debug:
#         var: brew_taps
#         verbosity: 1
#     - debug:
#         var: brew_formulas
#         verbosity: 1
#     - debug:
#         var: brew_casks
#         verbosity: 1
#   tags: always

- import_tasks: packages.yml
