---
- name: install homebrew
  debug:
    msg: "Not implemented"
  tags: install

- name: determine formulas
  set_fact:
    brew_formulas: "{{ q('dict', brew_formulas) | map(attribute='value') | list | flatten | unique }}"
  tags: always

  # when: brew_formulas is defined
- name: determine casks
  set_fact:
    brew_casks: "{{ q('dict', brew_casks) | map(attribute='value') | list | flatten | unique }}"
  tags: always

  # when: brew_casks is defined
# - debug:
#     var: brew_formulas
# - debug:
#     var: brew_casks

- import_tasks: packages.yml
