---
- name: update zplug
  block:
    - name: install missing plugins
      script: install_missing_plugins.zsh
      register: install
      changed_when: install.stdout.startswith('changed')
    - name: update plugins
      script: update_plugins.zsh
      register: update
      changed_when: update.stdout.startswith('changed')
  environment:
    ZPLUG_HOME: "{{ zplug_home }}"
    ZPLUG_PLUGS: "{{ ansible_user_dir }}/.dotfiles/plugins.zsh"
    ZPLUG_PIPE_FIX: true
