---
- name: install zplug
  block:
    - name: check if zplug is installed
      stat:
        path: "{{ zplug_home}}"
      register: zplug

    - name: run install script
      shell: >-
        curl -sL --proto-redir -all,https
        https://raw.githubusercontent.com/zplug/installer/master/installer.zsh
        | zsh > /dev/null 2>&1
      args:
        warn: false
      when: zplug.stat.isdir is not defined
      register: install
      notify: patch zplug add

    - name: wait until zplug_home is present before continuing
      wait_for:
        timeout: 10
        path: "{{ zplug_home }}"

    # flush handlers to patch zplug add
    - meta: flush_handlers

    - name: run zplug install
      script: install_missing_plugins.zsh
      when: install.changed
      notify: patch zplug add in repo

    # flush handlers to patch zplug add
    - meta: flush_handlers
  tags: install

- name: update zplug
  block:
    - name: install missing plugins
      script: install_missing_plugins.zsh
      register: install
      changed_when: install.stdout.startswith('changed')
    - name: update plugins
      script: update_plugins.zsh
      register: update
      changed_when: update.stdout.startswith('changed')
  tags: update
