---
- block:
    - name: "vim : check if vim-plug is installed"
      stat:
        path: "{{ vim_home }}/autoload/plug.vim"
      register: vim_plug

    - name: "vim : install vim-plug"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ vim_home }}/autoload/"
      when: vim_plug.stat.exists == False
      register: vim_plug_install

    - name: "vim : run PlugInstall"
      script: vim-plug-install.sh
      register: vim_plug_install
      changed_when: vim_plug_install.stdout.startswith("changed")
      when: vim_plug_install.changed
  tags: install

- block:
    - name: "vim : install missing plugins"
      script: vim-plug-install.sh
      register: vim_plug_install
      changed_when: vim_plug_install.stdout.startswith("changed")
    - name: "vim : update plugins"
      script: vim-plug-update.sh
      register: vim_plug_update
      changed_when: vim_plug_update.stdout.startswith("changed")
    - name: "vim : upgrade vim-plug"
      script: vim-plug-upgrade.sh
      register: vim_plug_upgrade
      changed_when: vim_plug_upgrade.stdout.startswith("changed")
  tags: update
