---
karabiner_config:
  path: keyboard/karabiner
  # Karabiner requires us to symlink the entire karabiner folder
  # rather than just the karabiner.json file.
  # https://pqrs.org/osx/karabiner/document.html#configuration-file-path
  link_entire_topic: true
  brew_casks:
    - karabiner-elements
