---
task_config:
  path: base/task
  links:
    - src: task_alacritty.sh
      dest: "{{ xdg_bin_home }}/"
      rename: task_alacritty
      # TODO: remove when v2.6 is released
    - src: taskrc
      dest: ~/
      rename: .taskrc
    - src: task_module.sh
      dest: "{{ xdg_bin_home }}/"
      rename: task_module
  brew_formulas:
    - task
  pacman_packages:
    - task
    - taskwarrior-tui
