---
hammerspoon_config:
  path: keyboard/hammerspoon
  links:
    - init.lua
    - modules
  brew_casks:
    - hammerspoon
  osx_defaults:
    - domain: org.hammerspoon.Hammerspoon
      key: MJConfigFile
      value: "{{ xdg_config_home }}/hammerspoon/init.lua"
      state: present
