---
- block:
    - debug:
        msg: "Linking topic {{ topic.config.path }}"

    - name: topic should be linked to xdg_data_home/dotfiles
      file:
        src: "{{ (topic.state == 'present') | ternary(link_src,omit) }}"
        path: "{{ topic_data_path }}"
        state: "{{ (topic.state == 'present') | ternary('link','absent') }}"
      vars:
        link_src: "{{ dotfiles + '/' + topic.config.path }}"
        link_path: "{{ topic_data_path }}"

    - name: topic should have a directory in xdg_config_home
      file:
        path: "{{ xdg_config_home + '/' + topic_config_dirname }}"
        state: "{{ (topic.state == 'present') | ternary('directory','absent') }}"
      when: topic.config.links is defined

    - name: link files
      file:
        src: "{{ (topic.state == 'present') | ternary(link_src,omit) }}"
        path: "{{ link_path }}"
        state: "{{ (topic.state == 'present') | ternary('link','absent') }}"
      vars:
        link_src: "{{ (item.absolute is defined and item.absolute) | ternary('',topic_data_path + '/') + (item.src | default(item)) }}"
        link_path: "{{ (item.dest | default(xdg_config_home + '/' + topic_config_dirname + '/')) | regex_replace('/$', '/' + (item.src | default(item))) }}"
      when: topic.config.links is defined
      loop: "{{ topic.config.links }}"
  vars:
    topic_data_path: "{{ dotfiles_data + '/' + (topic.config.path | replace('/', '.')) + '.topic' }}"
    topic_config_dirname: "{{ topic.config.dirname | default(topic.name) }}"
