---
vscode_config:
  path: editor/vscode
  brew_casks:
    - visual-studio-code
  links:
    - src: settings.json
      dest: "{{ vscode_home }}/"
    - src: keybindings.json
      dest: "{{ vscode_home }}/"
    - src: snippets
      dest: "{{ vscode_home }}/"
  osx_defaults:
    - domain: com.microsoft.VSCode
      key: ApplePressAndHoldEnabled
      value: false
      type: bool
      state: present
    - domain: com.microsoft.VSCodeInsiders
      key: ApplePressAndHoldEnabled
      value: false
      type: bool
      state: present

vscode_home: "~/Library/Application Support/Code/User"
