---
vscode_config:
  path: editor/vscode
  brew_casks:
    - visual-studio-code
  pacman_packages:
    - code
  links:
    - src: settings.json
      dest: "{{ vscode_home }}/"
    - src: keybindings.json
      dest: "{{ vscode_home }}/"
    - src: snippets
      dest: "{{ vscode_home }}/"
  osx_defaults:
    - domain: com.microsoft.VSCode
      key: ApplePressAndHoldEnabled
      value: false
      type: bool
      state: present
    - domain: com.microsoft.VSCodeInsiders
      key: ApplePressAndHoldEnabled
      value: false
      type: bool
      state: present

vscode_home_macos: "~/Library/Application Support/Code/User"
vscode_home_arch: "~/.config/Code/User"
vscode_home: "{{ vscode_home_macos if is_macos else vscode_home_arch }}"

vscode_plugins:
  - burkeholland.simple-react-snippets
  - CoenraadS.bracket-pair-colorizer
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  - ms-azuretools.vscode-docker
  - ms-python.python
  - ms-vsliveshare.vsliveshare
  - msjsdiag.debugger-for-chrome
  - PKief.material-icon-theme
  - ryuta46.multi-command
  - silvenon.mdx
  - teabyii.ayu
  - toba.vsfire
  - vscodevim.vim
  - WallabyJs.wallaby-vscode
  - whizkydee.material-palenight-theme
