---
node_config:
  path: lang/node
  brew_formulas:
    - node
    # - node@10
    - yarn
  pacman_packages:
    - nodejs
    - npm
    - yarn
  aur_packages:
    - nvm

npm_global_packages_dir: "{{ xdg_cache_home }}/npm-global"
