---
emacs_config:
  path: editor/emacs
  links:
    - src: doom
      dest: "{{ xdg_config_home }}/"
  brew_taps:
    - d12frosted/emacs-plus
  brew_formulas:
    - emacs-plus
    - gnupg  # Used by forge
  pacman_packages:
    - emacs
    - gnupg
  npm_packages:
    - typescript-language-server
    - typescript

doom_home: "~/.emacs.d"
