---
git_config:
  path: shell/git
  links:
    - config
    - ignore
  brew_formulas:
    - git
    - tig
    - hub
    - gh
    - diff-so-fancy
    # git-flow-avh
  pacman_packages:
    - git
    - tig
    - hub
    - github-cli
    - diff-so-fancy
  pip_packages:
    - grip
