---
git_config:
  path: shell/git
  links:
    - config
    - aliases
    - config-work
    - config-notes
    - ignore
  brew_formulas:
    - git
    - tig
    - hub
    - gh
    - diff-so-fancy
    - grip
    # git-flow-avh
  pacman_packages:
    - git
    - tig
    - hub
    - github-cli
    - diff-so-fancy
  aur_packages:
    - python-grip
