---
ssh_config:
  path: shell/ssh
  links:
    - src: config
      dest: "~/.ssh/"
    - src: macos.config
      dest: "~/.ssh/config.d/"
      condition: "{{ is_macos }}"
  brew_formulas:
    - ssh-copy-id
    - mosh
  pacman_packages:
    - mosh
