---
zsh_config:
  path: shell/zsh
  brew_formulas:
    # essentials
    - zsh
    - fzf
    - fd
    - bat
    - less
    - ripgrep
    - coreutils
    - watch
    - tree
    - mosh
    - ssh-copy-id
    # extras
    - jq
    - yq
    - pandoc
    # misc
    - neofetch
  pacman_packages:
    - zsh
    - xclip
    - fzf
    - fd
    - bat
    - ripgrep
    - tree
    - mosh
    - jq
    - yq
    - pandoc
    - neofetch
  links:
    - src: zshrc
      rename: .zshrc
    - src: zshenv
      rename: .zshenv
    - src: zshenv
      dest: ~/
      rename: .zshenv

zplug_home: "{{ xdg_cache_home }}/zplug"
