---
- hosts: mac

  vars_files:
    - default.config.yml

  roles:
    - role: eliasnorrby.dotfiles
      tags: dotfiles
    - role: geerlingguy.homebrew
      tags: never,do_homebrew,bootstrap
    - role: geerlingguy.mas
      tags: never,do_homebrew,bootstrap

  tasks:
    - include_tasks: extra-packages.yml
      tags: never,do_packages,bootstrap
    - include_tasks: osx-defaults.yml
      tags: never,do_defaults,bootstrap

    - name: run configured post-provision ansible task files
      include_tasks: "{{ outer_item }}"
      loop: "{{ post_provision_tasks | default(omit) }}"
      loop_control:
        loop_var: outer_item
