---
- name: " === pre-tasks === "
  hosts: machine
  tasks:
    - setup:
        gather_timeout: 10
      tags: always
# - name: " === prerequisites === "
#   hosts: machine
#   roles:
#     - homebrew

- name: " === shell === "
  hosts: machine
  # pre_tasks:
  #   setup:
  roles:
    - homebrew
    - zsh
    - tmux
    - alacritty
  tags: shell

# - name: " === editor === "
#   hosts: machine
#   roles:
#     - vim
#     - emacs

# - name: " === lang === "
#   hosts: machine
#   roles:
#     - java
#     - python
#     - node
#     - go

- name: " === base === "
  hosts: machine
  roles:
    # - keyboard
    - amethyst
    - apps
    # - development
