---
kubernetes_config:
  path: dev/kubernetes
  links:
    - src: k9s/skin.yml
      dest: ~/.k9s/
      rename: skin.yml
    - src: update_kubectl_token.sh
      dest: "{{ xdg_bin_home }}/"
      rename: update_kubectl_token
    - src: copy_and_update_kubectl_token.sh
      dest: "{{ xdg_bin_home }}/"
      rename: copy_and_update_kubectl_token
  brew_formulas:
    - minikube
    - kubectl
    - kind
    - kubeseal
    - openshift-cli
    - helm
    - kustomize
    - k9s
  pacman_packages:
    - minikube
    - kubectl
    - kubeseal
    - helm
    - kustomize
    - k9s
  aur_packages:
    - kind
    - origin-client
