---
kubernetes_config:
  path: dev/kubernetes
  brew_formulas:
    - minikube
    - kubectl
    - kind
    - kubeseal
    - openshift-cli
    # - docker-machine-driver-hyperkit
  pacman_packages:
    - minikube
    - kubectl
    - kubeseal
  aur_packages:
    - kind
    - origin-client
