---
kubernetes_config:
  path: dev/kubernetes
  brew_formulas:
    - minikube
    - kubectl
    - kind
    - kubeseal
    - openshift-cli
    - helm
    - kustomize
    - k9s
  pacman_packages:
    - minikube
    - kubectl
    - kubeseal
    - helm
    - kustomize
    - k9s
  aur_packages:
    - kind
    - origin-client
