---
kubernetes_config:
  path: dev/kubernetes
  links:
    - src: k9s/skin.yml
      dest: ~/.k9s/
  brew_formulas:
    - minikube
    - kubectl
    - kind
    - kubeseal
    - openshift-cli
    - helm
    - kustomize
    - k9s
  pacman_packages:
    - minikube
    - kubectl
    - kubeseal
    - helm
    - kustomize
    - k9s
  aur_packages:
    - kind
    - origin-client
