---
arch_config:
  path: base/arch
  links:
    - remap-caps-lock.sh
    - xinput.sh
    - src: Xresources
      dest: ~/.Xresources
  pacman_packages:
    - xcape
    - unzip
    - chromium
    - xorg-xinput
    - ttf-font-awesome
    - gucharmap
