---
arch_config:
  path: base/arch
  links:
    - xinput.sh
    - src: Xresources
      dest: ~/.Xresources
  pacman_packages:
    - unzip
    - chromium
    - xorg-xinput
    - xorg-xev
    - ttf-font-awesome
    - gucharmap
    - yay
