---
arch_config:
  path: base/arch
  links:
    - xinput.sh
    - src: Xresources
      dest: ~/.Xresources
    - src: focus_or_run.sh
      dest: "{{ xdg_bin_home }}/"
      rename: focus_or_run
    - src: gpg.conf
      dest: ~/.gnupg/
  pacman_packages:
    - unzip
    - chromium
    - xdotool
    - xorg-xinput
    - xorg-xev
    - ttf-font-awesome
    - gucharmap
    - yay
  aur_packages:
    - spotify

aur_builder_user_name: aur_builder
