---
arch_config:
  path: base/arch
  links:
    - xinput.sh
    - src: Xresources
      dest: ~/.Xresources
    - src: focus_or_run.sh
      dest: "{{ xdg_bin_home }}/"
      rename: focus_or_run
    - src: gpg.conf
      dest: ~/.gnupg/
    - autostart.sh
  pacman_packages:
    - ranger
    - unzip
    - chromium
    - discord
    - xdotool
    - xorg-xinput
    - xorg-xev
    - ttf-font-awesome
    - gucharmap
    - base-devel
    - yay
  aur_packages:
    - spotify
    - dropbox
    - nerd-fonts-fira-code
    - nerd-fonts-hack
    - nerd-fonts-iosevka
    - nerd-fonts-meslo
    - nerd-fonts-mononoki
    - nerd-fonts-source-code-pro

aur_builder_user_name: aur_builder
